// src/views/sensor/light/index.vue
<template>
  <el-card class="sensor-card">
    <template #header>
      <div class="card-header">
        <h3>光照监测</h3>
        <el-button :type="isRunning ? 'danger' : 'primary'" @click="isRunning ? handleStop() : handleStart()" :loading="loading">
          <el-icon><VideoPause v-if="isRunning" /><VideoPlay v-else /></el-icon>
          {{ isRunning ? '停止监测' : '开始监测' }}
        </el-button>
      </div>
    </template>

    <div v-if="chartData.length === 0" class="no-data">暂无数据</div>
    <div ref="chartRef" class="chart" v-else></div>
  </el-card>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { VideoPlay, VideoPause } from '@element-plus/icons-vue'
import { useSensor } from '@/composables/useSensor'
import * as echarts from 'echarts'

const { isRunning, loading, chartData, handleStart, handleStop } = useSensor(3, '光照')

const chartRef = ref<HTMLElement>()
let chart: echarts.ECharts | null = null

const renderChart = () => {
  if (!chartRef.value || chartData.value.length === 0) return
  if (!chart) {
    chart = echarts.init(chartRef.value)
  }

  chart.setOption({
    tooltip: { trigger: 'axis' },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.value.map((d) => d.time),
      name: '时间',
    },
    yAxis: {
      type: 'value',
      name: '光照强度 (kLux)',
      min: 0,
      max: 100,
      interval: 10,
      axisLabel: { formatter: (value: number) => value + 'k' },
    },
    series: [
      {
        data: chartData.value.map((d) => d.value),
        type: 'line',
        smooth: true,
        itemStyle: { color: '#faad14' },
        areaStyle: {
          opacity: 0.6,
          color: {
            type: 'linear',
            x: 0, y: 0, x2: 0, y2: 1,
            colorStops: [
              { offset: 0, color: '#faad14' },
              { offset: 1, color: 'rgba(250, 173, 20, 0.1)' },
            ],
          },
        },
        lineStyle: { width: 2 },
      },
    ],
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
  })
}

watch(chartData, () => renderChart(), { deep: true })

onMounted(() => {
  if (chartData.value.length > 0) {
    setTimeout(() => renderChart(), 100)
  }
})

onUnmounted(() => {
  chart?.dispose()
})
</script>

<style scoped lang="less">
.sensor-card {
  :deep(.el-card__header) {
    padding: 16px 24px;
  }
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;

  h3 {
    margin: 0;
    font-size: 18px;
    font-weight: 600;
  }
}

.no-data {
  height: 70vh;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #999;
  font-size: 16px;
}

.chart {
  height: 70vh;
  width: 100%;
}
</style>

// src/pages/Sensor/light/index.tsx
import React, {useEffect, useRef, useState} from 'react';
import {Button, Card, message, Spin} from 'antd';
import {PlayCircleOutlined, StopOutlined} from '@ant-design/icons';
import {getSensorStatus, readSensorData, startSensor, stopSensor} from '@/services/ant-design-pro/api';
import ReactECharts from 'echarts-for-react';

const LightSensorPage: React.FC = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [loading, setLoading] = useState(false);
  const [chartData, setChartData] = useState<any[]>([]);
  const timerRef = useRef<NodeJS.Timeout>();

  const fetchStatus = async () => {
    try {
      console.log('光照: 获取传感器状态...');
      const res = await getSensorStatus(3);
      console.log('光照: 状态响应', res);
      const running = res?.running ?? res?.data?.running ?? false;
      console.log('光照: 设置运行状态为', running);
      setIsRunning(running);
    } catch (error) {
      console.error('光照: 获取状态失败', error);
    }
  };

  const fetchInitialData = async () => {
    try {
      const res = await readSensorData(3, 5);
      console.log('光照初始数据:', JSON.stringify(res, null, 2));
      if (res && Array.isArray(res)) {
        const formatted = res.map((item: any) => ({
          time: item.collect_time || new Date(item.createTime || Date.now()).toLocaleTimeString(),
          value: parseFloat(item.col1 || item.value || item.lightValue || 0),
        }));
        formatted.sort((a: any, b: any) => new Date(a.time).getTime() - new Date(b.time).getTime());
        setChartData(formatted);
      }
    } catch (error) {
      console.error('获取初始数据失败', error);
    }
  };

  const fetchData = async () => {
    try {
      const res = await readSensorData(3, 1);
      console.log('光照最新数据:', JSON.stringify(res, null, 2));
      if (res && Array.isArray(res)) {
        const newItem = {
          time: res[0].collect_time || new Date(res[0].createTime || Date.now()).toLocaleTimeString(),
          value: parseFloat(res[0].col1 || res[0].value || res[0].lightValue || 0),
        };
        setChartData(prev => {
          const updated = [...prev, newItem];
          return updated.slice(-5);
        });
      }
    } catch (error) {
      console.error('获取数据失败', error);
    }
  };

  const handleStart = async () => {
    setLoading(true);
    try {
      await startSensor(3);
      message.success('光照监测已启动');
      // 重新获取状态确认
      await fetchStatus();
    } catch (error) {
      message.error('启动失败');
    } finally {
      setLoading(false);
    }
  };

  const handleStop = async () => {
    setLoading(true);
    try {
      await stopSensor(3);
      message.success('光照监测已停止');
      // 重新获取状态确认
      await fetchStatus();
    } catch (error) {
      message.error('停止失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStatus();
    fetchInitialData();
    // 定时刷新状态，确保与后端同步
    const statusTimer = setInterval(fetchStatus, 5000);
    return () => clearInterval(statusTimer);
  }, []);

  useEffect(() => {
    stopPolling();
    if (isRunning) {
      // 先立即获取一次数据
      fetchData();
      timerRef.current = setInterval(fetchData, 2000);
    }
    return () => stopPolling();
  }, [isRunning]);

  const stopPolling = () => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = undefined;
    }
  };

  const chartOption = chartData.length > 0 ? {
    title: {
      text: '光照监测',
      left: 'center',
    },
    tooltip: {
      trigger: 'axis',
    },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.map((d) => d.time),
      name: '时间',
    },
    yAxis: {
      type: 'value',
      name: '光照强度 (kLux)',
      min: 0,
      max: 100,
      interval: 10,
      axisLabel: {
        formatter: (value: number) => value + 'k',
      },
    },
    series: [
      {
        data: chartData.map((d) => d.value),
        type: 'line',
        smooth: true,
        itemStyle: { color: '#faad14' },
        areaStyle: {
          opacity: 0.6,
          color: {
            type: 'linear',
            x: 0, y: 0, x2: 0, y2: 1,
            colorStops: [
              { offset: 0, color: '#faad14' },
              { offset: 1, color: 'rgba(250, 173, 20, 0.1)' },
            ],
          },
        },
        lineStyle: {
          width: 2,
        },
        animation: true,
        animationDuration: 600,
        animationEasing: 'cubicOut',
      },
    ],
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true,
    },
  } : null;

  return (
    <Card
      title="光照监测"
      extra={
        <Button
          type={isRunning ? 'danger' : 'primary'}
          icon={isRunning ? <StopOutlined /> : <PlayCircleOutlined />}
          onClick={isRunning ? handleStop : handleStart}
          loading={loading}
        >
          {isRunning ? '停止监测' : '开始监测'}
        </Button>
      }
    >
      <Spin spinning={loading && chartData.length === 0}>
        {chartData.length > 0 && chartOption ? (
          <ReactECharts option={chartOption} style={{ height: '70vh' }} notMerge={false} />
        ) : (
          <div style={{ height: '70vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            暂无数据
          </div>
        )}
      </Spin>
    </Card>
  );
};

export default LightSensorPage;
