// src/pages/Sensor/humidity/index.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Card, Button, message, Spin } from 'antd';
import { PlayCircleOutlined, StopOutlined } from '@ant-design/icons';
import { startSensor, stopSensor, getSensorStatus, readSensorData } from '@/services/ant-design-pro/api';
import ReactECharts from 'echarts-for-react';

const HumiditySensorPage: React.FC = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [loading, setLoading] = useState(false);
  const [chartData, setChartData] = useState<any[]>([]);
  const timerRef = useRef<NodeJS.Timeout>();

  const fetchStatus = async () => {
    try {
      const res = await getSensorStatus(2);
      console.log('湿度 状态响应:', res);
      let running = false;
      if (typeof res === 'boolean') running = res;
      else if (typeof res === 'string') running = res === '运行中' || res === 'running';
      else if (res) {
        if (res.source_2) running = res.source_2 === '运行中';
        else if (res.running !== undefined) running = res.running === true;
        else if (res.data) running = parseStatus(res.data, 2);
      }
      setIsRunning(running);
    } catch (error) {
      console.error('湿度 获取状态失败', error);
    }
  };

  const parseStatus = (data: any, source: number): boolean => {
    if (typeof data === 'boolean') return data;
    if (typeof data === 'string') return data === '运行中' || data === 'running';
    if (data) {
      const key = `source_${source}`;
      if (data[key]) return data[key] === '运行中';
      if (data.running !== undefined) return data.running === true;
    }
    return false;
  };

  const fetchInitialData = async () => {
    try {
      const res = await readSensorData(2, 5);
      console.log('湿度初始数据:', JSON.stringify(res, null, 2));
      if (res && Array.isArray(res)) {
        const formatted = res.map((item: any) => ({
          time: item.collect_time || new Date(item.createTime || Date.now()).toLocaleTimeString(),
          value: parseFloat(item.col1 || item.value || item.humidityValue || 0),
        }));
        formatted.sort((a: any, b: any) => new Date(a.time).getTime() - new Date(b.time).getTime());
        setChartData(formatted);
      }
    } catch (error) {
      console.error('获取初始数据失败', error);
    }
  };

  const fetchData = async () => {
    try {
      const res = await readSensorData(2, 1);
      console.log('湿度最新数据:', JSON.stringify(res, null, 2));
      if (res && Array.isArray(res)) {
        const newItem = {
          time: res[0].collect_time || new Date(res[0].createTime || Date.now()).toLocaleTimeString(),
          value: parseFloat(res[0].col1 || res[0].value || res[0].humidityValue || 0),
        };
        setChartData(prev => {
          const updated = [...prev, newItem];
          return updated.slice(-5);
        });
      }
    } catch (error) {
      console.error('获取数据失败', error);
    }
  };

  const handleStart = async () => {
    setLoading(true);
    try {
      await startSensor(2);
      message.success('湿度监测已启动');
      setIsRunning(true);
    } catch (error) {
      message.error('启动失败');
    } finally {
      setLoading(false);
    }
  };

  const handleStop = async () => {
    setLoading(true);
    try {
      await stopSensor(2);
      message.success('湿度监测已停止');
      setIsRunning(false);
    } catch (error) {
      message.error('停止失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStatus();
    fetchInitialData();
    const statusInterval = setInterval(fetchStatus, 3000);
    return () => clearInterval(statusInterval);
  }, []);

  useEffect(() => {
    stopPolling();
    if (isRunning) {
      fetchData();
      timerRef.current = setInterval(fetchData, 2000);
    }
    return () => stopPolling();
  }, [isRunning]);

  const stopPolling = () => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = undefined;
    }
  };

  const chartOption = chartData.length > 0 ? {
    title: {
      text: '',
      left: 'center',
    },
    tooltip: {
      trigger: 'axis',
    },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.map((d) => d.time),
      name: '时间',
    },
    yAxis: {
      type: 'value',
      name: '湿度 (%RH)',
      min: 0,
      max: 100,
      interval: 10,
    },
    series: [
      {
        data: chartData.map((d) => d.value),
        type: 'bar',
        itemStyle: {
          color: '#3098d6',
          borderRadius: [4, 4, 0, 0],
        },
        animation: true,
        animationDuration: 600,
        animationEasing: 'cubicOut',
      },
    ],
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true,
    },
  } : null;

  return (
    <Card
      title={<div style={{ textAlign: 'center', width: '100%' }}>湿度监测</div>}
      extra={
        <Button
          type={isRunning ? 'danger' : 'primary'}
          icon={isRunning ? <StopOutlined /> : <PlayCircleOutlined />}
          onClick={isRunning ? handleStop : handleStart}
          loading={loading}
        >
          {isRunning ? '停止监测' : '开始监测'}
        </Button>
      }
    >
      <Spin spinning={loading && chartData.length === 0}>
        {chartData.length > 0 && chartOption ? (
          <ReactECharts option={chartOption} style={{ height: '70vh' }} notMerge={false} />
        ) : (
          <div style={{ height: '70vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            暂无数据
          </div>
        )}
      </Spin>
    </Card>
  );
};

export default HumiditySensorPage;

// src/views/sensor/humidity/index.vue
<template>
  <el-card class="sensor-card">
    <template #header>
      <div class="card-header">
        <h3>湿度监测</h3>
        <el-button :type="isRunning ? 'danger' : 'primary'" @click="isRunning ? handleStop() : handleStart()" :loading="loading">
          <el-icon><VideoPause v-if="isRunning" /><VideoPlay v-else /></el-icon>
          {{ isRunning ? '停止监测' : '开始监测' }}
        </el-button>
      </div>
    </template>

    <div v-if="chartData.length === 0" class="no-data">暂无数据</div>
    <div ref="chartRef" class="chart" v-else></div>
  </el-card>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { VideoPlay, VideoPause } from '@element-plus/icons-vue'
import { useSensor } from '@/composables/useSensor'
import * as echarts from 'echarts'

const { isRunning, loading, chartData, handleStart, handleStop } = useSensor(2, '湿度')

const chartRef = ref<HTMLElement>()
let chart: echarts.ECharts | null = null

const renderChart = () => {
  if (!chartRef.value || chartData.value.length === 0) return
  if (!chart) {
    chart = echarts.init(chartRef.value)
  }

  chart.setOption({
    tooltip: { trigger: 'axis' },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.value.map((d) => d.time),
      name: '时间',
    },
    yAxis: {
      type: 'value',
      name: '湿度 (%RH)',
      min: 0,
      max: 100,
      interval: 10,
    },
    series: [
      {
        data: chartData.value.map((d) => d.value),
        type: 'bar',
        itemStyle: {
          color: '#3098d6',
          borderRadius: [4, 4, 0, 0],
        },
      },
    ],
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
  })
}

watch(chartData, () => renderChart(), { deep: true })

onMounted(() => {
  if (chartData.value.length > 0) {
    setTimeout(() => renderChart(), 100)
  }
})

onUnmounted(() => {
  chart?.dispose()
})
</script>

<style scoped lang="less">
.sensor-card {
  :deep(.el-card__header) {
    padding: 16px 24px;
  }
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;

  h3 {
    margin: 0;
    font-size: 18px;
    font-weight: 600;
  }
}

.no-data {
  height: 70vh;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #999;
  font-size: 16px;
}

.chart {
  height: 70vh;
  width: 100%;
}
</style>
