// src/pages/Sensor/gps/index.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Card, Button, message, Spin, Alert } from 'antd';
import { PlayCircleOutlined, StopOutlined } from '@ant-design/icons';
import { startSensor, stopSensor, getSensorStatus, readSensorData } from '@/services/ant-design-pro/api';
import ReactECharts from 'echarts-for-react';

const GpsSensorPage: React.FC = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [loading, setLoading] = useState(false);
  const [chartData, setChartData] = useState<any[]>([]);
  const [error, setError] = useState<string>('');
  const timerRef = useRef<NodeJS.Timeout>();

  const fetchStatus = async () => {
    try {
      const res = await getSensorStatus(1);
      console.log('GPS 状态响应:', res);
      let running = false;
      if (typeof res === 'boolean') running = res;
      else if (typeof res === 'string') running = res === '运行中' || res === 'running';
      else if (res) {
        if (res.source_1) running = res.source_1 === '运行中';
        else if (res.running !== undefined) running = res.running === true;
        else if (res.data) running = fetchStatusFromRes(res.data);
      }
      setIsRunning(running);
    } catch (error: any) {
      console.error('获取状态失败', error);
    }
  };

  const fetchStatusFromRes = (data: any): boolean => {
    if (typeof data === 'boolean') return data;
    if (typeof data === 'string') return data === '运行中' || data === 'running';
    if (data) {
      if (data.source_1) return data.source_1 === '运行中';
      if (data.running !== undefined) return data.running === true;
    }
    return false;
  };

  const fetchInitialData = async () => {
    try {
      setError('');
      // 首次进入获取最近5条数据
      const res = await readSensorData(1, 5);
      console.log('GPS初始数据:', JSON.stringify(res, null, 2));

      let dataArray = null;
      if (Array.isArray(res)) {
        dataArray = res;
      } else if (res && Array.isArray(res.data)) {
        dataArray = res.data;
      }

      if (dataArray && dataArray.length > 0) {
        const newData = dataArray.map((item: any) => ({
          time: item.collect_time || new Date().toLocaleTimeString(),
          value: parseFloat(item.col1 || 0),
        }));
        // 按时间正序排列，确保最新的在右侧
        newData.sort((a: any, b: any) => new Date(a.time).getTime() - new Date(b.time).getTime());
        setChartData(newData);
      }
    } catch (error: any) {
      console.error('获取初始数据失败', error);
    }
  };

  const fetchData = async () => {
    try {
      setError('');
      // 只获取最新1条数据
      const res = await readSensorData(1, 1);
      console.log('GPS最新数据:', JSON.stringify(res, null, 2));

      let dataArray = null;
      if (Array.isArray(res)) {
        dataArray = res;
      } else if (res && Array.isArray(res.data)) {
        dataArray = res.data;
      }

      if (dataArray && dataArray.length > 0) {
        const newItem = {
          time: dataArray[0].collect_time || new Date().toLocaleTimeString(),
          value: parseFloat(dataArray[0].col1 || 0),
        };

        // 追加新数据，保留最新5条
        setChartData(prev => {
          const updated = [...prev, newItem];
          return updated.slice(-5); // 只保留最后5条
        });
      }
    } catch (error: any) {
      console.error('获取数据失败', error);
    }
  };

  const handleStart = async () => {
    setLoading(true);
    try {
      await startSensor(1);
      message.success('GPS监测已启动');
      setIsRunning(true);
    } catch (error: any) {
      message.error('启动失败');
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  const handleStop = async () => {
    setLoading(true);
    try {
      await stopSensor(1);
      message.success('GPS监测已停止');
      setIsRunning(false);
    } catch (error: any) {
      message.error('停止失败');
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStatus();
    fetchInitialData();
    // 每3秒同步一次状态，确保跳转页面后状态正确
    const statusInterval = setInterval(fetchStatus, 3000);
    return () => clearInterval(statusInterval);
  }, []);

  useEffect(() => {
    stopPolling();
    if (isRunning) {
      fetchData();
      timerRef.current = setInterval(fetchData, 2000);
    }
    return () => stopPolling();
  }, [isRunning]);

  const stopPolling = () => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = undefined;
    }
  };

  const chartOption = chartData.length > 0 ? {
    title: {
      text: '',
      left: 'center',
    },
    tooltip: {
      trigger: 'axis',
    },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.map((d) => d.time),
      name: '创建时间',
    },
    yAxis: {
      type: 'value',
      name: '海拔 (m)',
      min: 0,
      max: 9000,
      interval: 500,
      axisLabel: {
        show: true,
      },
      splitLine: {
        show: true,
        lineStyle: {
          type: 'dashed',
          opacity: 0.3,
        },
      },
    },
    series: [
      {
        data: chartData.map((d) => d.value),
        type: 'line',
        smooth: true,
        itemStyle: { color: '#bc7c26' },
        areaStyle: {
          opacity: 0.3,
          color: '#ffffff',
        },
        animation: true,
        animationDuration: 600,
        animationEasing: 'cubicOut',
      },
    ],
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true,
    },
  } : null;

  return (
    <Card
      title={<div style={{ textAlign: 'center', width: '100%' }}>GPS监测</div>}
      extra={
        <Button
          type={isRunning ? 'danger' : 'primary'}
          icon={isRunning ? <StopOutlined /> : <PlayCircleOutlined />}
          onClick={isRunning ? handleStop : handleStart}
          loading={loading}
        >
          {isRunning ? '停止监测' : '开始监测'}
        </Button>
      }
    >
      {error && (
        <Alert message={error} type="error" showIcon style={{ marginBottom: 16 }} />
      )}
      <Spin spinning={loading && chartData.length === 0}>
        {chartData.length > 0 && chartOption ? (
          <ReactECharts option={chartOption} style={{ height: '70vh' }} notMerge={false} />
        ) : (
          <div style={{ height: '70vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            暂无数据
          </div>
        )}
      </Spin>
    </Card>
  );
};

export default GpsSensorPage;

// src/views/sensor/gps/index.vue
<template>
  <el-card class="sensor-card">
    <template #header>
      <div class="card-header">
        <h3>GPS监测</h3>
        <el-button :type="isRunning ? 'danger' : 'primary'" @click="isRunning ? handleStop() : handleStart()" :loading="loading">
          <el-icon><VideoPause v-if="isRunning" /><VideoPlay v-else /></el-icon>
          {{ isRunning ? '停止监测' : '开始监测' }}
        </el-button>
      </div>
    </template>

    <div v-if="chartData.length === 0" class="no-data">暂无数据</div>
    <div ref="chartRef" class="chart" v-else></div>
  </el-card>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { VideoPlay, VideoPause } from '@element-plus/icons-vue'
import { useSensor } from '@/composables/useSensor'
import * as echarts from 'echarts'

const { isRunning, loading, chartData, handleStart, handleStop } = useSensor(1, 'GPS')

const chartRef = ref<HTMLElement>()
let chart: echarts.ECharts | null = null

const renderChart = () => {
  if (!chartRef.value || chartData.value.length === 0) return
  if (!chart) {
    chart = echarts.init(chartRef.value)
  }

  chart.setOption({
    tooltip: { trigger: 'axis' },
    animation: true,
    animationDuration: 600,
    animationEasing: 'cubicOut',
    xAxis: {
      type: 'category',
      data: chartData.value.map((d) => d.time),
      name: '创建时间',
    },
    yAxis: {
      type: 'value',
      name: '海拔 (m)',
      min: 0,
      max: 9000,
      interval: 500,
      splitLine: {
        show: true,
        lineStyle: { type: 'dashed', opacity: 0.3 },
      },
    },
    series: [
      {
        data: chartData.value.map((d) => d.value),
        type: 'line',
        smooth: true,
        itemStyle: { color: '#bc7c26' },
        areaStyle: { opacity: 0.3, color: '#ffffff' },
      },
    ],
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
  })
}

watch(chartData, () => renderChart(), { deep: true })

onMounted(() => {
  if (chartData.value.length > 0) {
    setTimeout(() => renderChart(), 100)
  }
})

onUnmounted(() => {
  chart?.dispose()
})
</script>

<style scoped lang="less">
.sensor-card {
  :deep(.el-card__header) {
    padding: 16px 24px;
  }
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;

  h3 {
    margin: 0;
    font-size: 18px;
    font-weight: 600;
  }
}

.no-data {
  height: 70vh;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #999;
  font-size: 16px;
}

.chart {
  height: 70vh;
  width: 100%;
}
</style>
