// src/pages/user/Login/index.tsx
import {LockOutlined, UserOutlined,} from '@ant-design/icons';
import {Alert, message, Tabs} from 'antd';
import React, {useState} from 'react';
import {LoginForm, ProFormCheckbox, ProFormText} from '@ant-design/pro-form';
import {history, useModel} from 'umi';
import {SYSTEM_LOGO} from '@/constants';
import {login} from '@/services/ant-design-pro/api';
import styles from './index.less';
import {Link} from "@umijs/preset-dumi/lib/theme";
import Footer from "@/components/Footer";

const LoginMessage: React.FC<{
  content: string;
}> = ({content}) => (
  <Alert
    style={{
      marginBottom: 24,
    }}
    message={content}
    type="error"
    showIcon
  />
);

const Login: React.FC = () => {
  const [userLoginState] = useState<API.LoginResult>({});
  const [type, setType] = useState<string>('account');
  const {initialState, setInitialState} = useModel('@@initialState');

  const fetchUserInfo = async () => {
    const userInfo = await initialState?.fetchUserInfo?.();

    if (userInfo) {
      await setInitialState((s) => ({...s, currentUser: userInfo}));
    }
  };

  const handleSubmit = async (values: API.LoginParams) => {
    try {
      // 登录
      const user = await login({...values, type});

      if (user) {
        const defaultLoginSuccessMessage = '登录成功！';
        message.success(defaultLoginSuccessMessage);
        await fetchUserInfo();
        /** 根据用户身份跳转 */

        if (!history) return;
        const {query} = history.location;
        const {redirect} = query as {
          redirect: string;
        };

        // 检查 redirect 路径是否与用户角色匹配
        const isAdminPath = redirect?.startsWith('/admin');
        const isAdminUser = user.userRole === 1;

        // 普通用户尝试访问管理员页面时跳转到其默认首页
        if (redirect && (!isAdminPath || isAdminUser)) {
          history.push(redirect);
        } else if (isAdminUser) {
          history.push('/admin/user-manage');
        } else {
          history.push('/sensor/gps');
        }
        return;
      } else {
        message.error('用户名或密码错误');
      }
    } catch (error) {
      const defaultLoginFailureMessage = '登录失败，请重试！';
      message.error(defaultLoginFailureMessage);
    }
  };

  const {status, type: loginType} = userLoginState;
  return (
    <div className={styles.container}>
      <div className={styles.content}>
        <LoginForm
          logo={<img alt="logo" src={SYSTEM_LOGO}/>}
          title="环境监测系统"
          initialValues={{
            autoLogin: true,
          }}
          onFinish={async (values) => {
            await handleSubmit(values as API.LoginParams);
          }}
        >
          <Tabs activeKey={type} onChange={setType}>
            <Tabs.TabPane key="account" tab={'用户登录'}/>
          </Tabs>
          {status === 'error' && loginType === 'account' && (
            <LoginMessage content={'账号或密码错误'}/>
          )}
          {type === 'account' && (
            <>
              <div className={styles.fieldLabel}>账号</div>
              <ProFormText
                name="userAccount"
                fieldProps={{
                  size: 'large',
                  prefix: <UserOutlined className={styles.prefixIcon}/>,
                }}
                placeholder="请输入账号"
                rules={[
                  {
                    required: true,
                    message: '账号是必填项！',
                  },
                ]}
              />
              <div className={styles.fieldLabel}>密码</div>
              <ProFormText.Password
                name="userPassword"
                fieldProps={{
                  size: 'large',
                  prefix: <LockOutlined className={styles.prefixIcon}/>,
                }}
                placeholder="请输入密码"
                rules={[
                  {
                    required: true,
                    message: '密码是必填项！',
                  },
                  {
                    min: 8,
                    type: 'string',
                    message: '长度不能小于 8',
                  },
                ]}
              />
            </>
          )}
          <div className={styles.actions}>
            <div className={styles.leftAction}>
              <ProFormCheckbox noStyle name="autoLogin">
                自动登录
              </ProFormCheckbox>
            </div>
            <div className={styles.rightAction}>
              <Link to="/user/register" className={styles.registerLink}>用户注册</Link>
            </div>
          </div>
        </LoginForm>
      </div>
      <Footer/>
    </div>
  );
};

export default Login;

// src/views/user/Login.vue
<template>
  <div class="login-container">
    <el-card class="login-card">
      <template #header>
        <div class="login-header">
          <img :src="logoUrl" alt="logo" class="logo" />
          <h2>环境监测系统</h2>
        </div>
      </template>

      <el-tabs v-model="activeTab" class="login-tabs">
        <el-tab-pane label="用户登录" name="account" />
      </el-tabs>

      <el-alert v-if="errorMsg" :title="errorMsg" type="error" show-icon closable @close="errorMsg = ''" />

      <el-form ref="formRef" :model="form" :rules="rules" label-position="top" @submit.prevent="handleSubmit">
        <div class="field-label">账号</div>
        <el-form-item prop="userAccount">
          <el-input v-model="form.userAccount" size="large" placeholder="请输入账号">
            <template #prefix>
              <el-icon><User /></el-icon>
            </template>
          </el-input>
        </el-form-item>

        <div class="field-label">密码</div>
        <el-form-item prop="userPassword">
          <el-input v-model="form.userPassword" type="password" size="large" placeholder="请输入密码" show-password>
            <template #prefix>
              <el-icon><Lock /></el-icon>
            </template>
          </el-input>
        </el-form-item>

        <div class="actions">
          <el-checkbox v-model="form.autoLogin">自动登录</el-checkbox>
          <router-link to="/user/register" class="register-link">用户注册</router-link>
        </div>

        <el-form-item>
          <el-button type="primary" size="large" style="width: 100%" :loading="loading" native-type="submit">
            登录
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Lock } from '@element-plus/icons-vue'
import { login } from '@/api'
import { useUserStore } from '@/stores/user'
import type { FormInstance, FormRules } from 'element-plus'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()

const logoUrl = 'http://mms0.baidu.com/it/u=604189734,1143451865&fm=253&app=138&f=JPEG?w=250&h=250'
const activeTab = ref('account')
const errorMsg = ref('')
const loading = ref(false)
const formRef = ref<FormInstance>()

const form = reactive({
  userAccount: '',
  userPassword: '',
  autoLogin: true,
  type: 'account',
})

const rules: FormRules = {
  userAccount: [{ required: true, message: '账号是必填项！', trigger: 'blur' }],
  userPassword: [
    { required: true, message: '密码是必填项！', trigger: 'blur' },
    { min: 8, message: '长度不能小于 8', trigger: 'blur' },
  ],
}

const handleSubmit = async () => {
  if (!formRef.value) return
  await formRef.value.validate(async (valid) => {
    if (!valid) return

    loading.value = true
    try {
      const res = await login({ ...form })
      if (res) {
        ElMessage.success('登录成功！')
        await userStore.fetchUserInfo()

        const redirect = route.query.redirect as string
        const isAdminPath = redirect?.startsWith('/admin')
        const isAdminUser = userStore.currentUser?.userRole === 1

        if (redirect && (!isAdminPath || isAdminUser)) {
          router.push(redirect)
        } else if (isAdminUser) {
          router.push('/admin/user-manage')
        } else {
          router.push('/sensor/gps')
        }
      } else {
        errorMsg.value = '用户名或密码错误'
      }
    } catch {
      errorMsg.value = '登录失败，请重试！'
    } finally {
      loading.value = false
    }
  })
}
</script>

<style scoped lang="less">
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  max-width: 480px;
  margin: 0 auto;
  padding: 0 24px;
}

.login-card {
  width: 100%;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);

  :deep(.el-card__header) {
    padding: 24px 24px 0;
    border: none;
  }

  :deep(.el-card__body) {
    padding: 16px 24px 24px;
  }
}

.login-header {
  text-align: center;
  margin-bottom: 16px;

  .logo {
    width: 48px;
    height: 48px;
    margin-bottom: 8px;
  }

  h2 {
    margin: 0;
    font-size: 22px;
    font-weight: 600;
    color: #1a1a1a;
  }
}

.login-tabs {
  margin-bottom: 20px;

  :deep(.el-tabs__header) {
    margin-bottom: 20px;
  }
}

.field-label {
  margin-bottom: 8px;
  font-weight: 500;
  color: rgba(0, 0, 0, 0.65);
  font-size: 14px;
}

.actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.register-link {
  color: #1890ff;
  text-decoration: none;
  font-size: 14px;

  &:hover {
    color: #40a9ff;
  }
}
</style>
